### ISSUE TITLE
Allow cert to be the actual certificate string

### ISSUE THREAD

**Issue by natematykiewicz** [ostinelli/apnotic#120]
We use Rails credentials. I'd like to store my certificate in the credentials store like:

```yaml
apns:
  team_id: 1234
  key_id: 5678
  certificate: |-
    -----BEGIN PRIVATE KEY-----
    Key content goes here
    -----END PRIVATE KEY-----
```

And then configure Apnotic like:

```ruby
Apnotic::ConnectionPool.new({
  auth_method: :token,
  cert: Rails.application.credentials.dig(:apns, :certificate),
  team_id: Rails.application.credentials.dig(:apns, :team_id),
  key_id: Rails.application.credentials.dig(:apns, :key_id),
}, size: 5) do |connection|
  connection.on(:error) { |exception| puts "Exception has been raised: #{exception}" }
end
```

This would mean that our certificate is never written to disk in plain text at all. But also, it means the certificate can be included in the repo with the rest of our credentials, because they're encrypted.

Would you be open to a feature that added `cert` as an option? I think it's as easy as allowing `cert` to be specified in the options hash, and then setting `@certificate = options[:cert]` in [the initializer](https://github.com/ostinelli/apnotic/blob/5e804cd0c9b394472e17c84f679727ec4501766f/lib/apnotic/connection.rb#L20). Then, the actual `certificate` method [won't reassign it](https://github.com/ostinelli/apnotic/blob/5e804cd0c9b394472e17c84f679727ec4501766f/lib/apnotic/connection.rb#L131), because it does `||=`.
